name:               "Dr. Hao Li"
description:        "National University of Singapore"

url:                ""
author:             "Hao Li"
email:              "hao.li@nus.edu.sg"
twitter:            "bobleegogogo"
github:             "bobleegogogo"
linkedin:           "hao-li-340868154"
googlescholar:      "citations?user=yECGOCwAAAAJ&hl=en"


disqus_shortname:   "Hao"

background:         "/1658027027.jpg"
#"http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           8
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown
    
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Research"
    href:           "/research"
  - name:           "Teaching"
    href:           "/teaching"
  - name:           "Gallery"
    href:           "/gallery"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

highlighter: rouge
